stages:
  - test-python3-latest
  - test-python2-latest
  - build
  - deploy

test-python3-latest:
  stage: test-python3-latest
  image: python:3
  script:
  - pip install .
  - python -m pytest

test-python2-latest:
  stage: test-python2-latest
  image: python:2
  script:
  - pip install .
  - python -m pytest

build-epydocs:
  stage: build
  image: python:2
  script:
  - pip install .
  - make epydocs
  artifacts:
    paths:
    - epydocs/

pages:
  stage: deploy
  dependencies:
  - build-epydocs
  only:
  - master
  - gl-pages
  image: python:2
  script:
  - mkdir public/
  - mv epydocs/ public/epydocs/
  artifacts:
    paths:
    - public
